<?php $properties["fprops"]=array(
array('name'=>'to','label'=>'to','type'=>'text','is_transient'=>true,'srcName'=>'to','ufname'=>'_to','qname'=>'rct_vacancy_provider_to','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'subject','label'=>'subject','type'=>'text','is_transient'=>true,'srcName'=>'subject','ufname'=>'_subject','qname'=>'rct_vacancy_provider_subject','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'body','label'=>'body','type'=>'text','is_transient'=>true,'srcName'=>'body','ufname'=>'_body','qname'=>'rct_vacancy_provider_body','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'files','label'=>'files','type'=>'text','is_transient'=>true,'srcName'=>'files','ufname'=>'_files','qname'=>'rct_vacancy_provider_files','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('to'=>'to','_to'=>'to','subject'=>'subject','_subject'=>'subject','body'=>'body','_body'=>'body','files'=>'files','_files'=>'files',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy_provider.email_data','table'=>'_rct_vacancy_provider');
 ?>