<?php $properties["fprops"]=array(
array('name'=>'name','label'=>'name','type'=>'text','srcName'=>'name','ufname'=>'_name','qname'=>'rct_vacancy_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('name'=>'name','_name'=>'name',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy.find_name_by_oid','table'=>'_rct_vacancy');
 ?>