<?php $properties["fprops"]=array(
array('name'=>'rct_vacancy_readonly_oid','label'=>'oid','type'=>'text','isKey'=>'primary','show'=>false,'isEdit'=>false,'srcName'=>'oid','ufname'=>'rct_vacancy_readonly_oid','qname'=>'rct_vacancy_readonly_oid','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),
array('name'=>'rct_vacancy_readonly_key','type'=>'text','label'=>'key','srcName'=>'key','ufname'=>'rct_vacancy_readonly_key','qname'=>'rct_vacancy_readonly_key','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),
array('name'=>'rct_vacancy_readonly_val','type'=>'text','label'=>'val','srcName'=>'val','ufname'=>'rct_vacancy_readonly_val','qname'=>'rct_vacancy_readonly_val','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('oid'=>'rct_vacancy_readonly_oid','oid'=>'rct_vacancy_readonly_oid','_oid'=>'rct_vacancy_readonly_oid','key'=>'rct_vacancy_readonly_key','key'=>'rct_vacancy_readonly_key','_key'=>'rct_vacancy_readonly_key','val'=>'rct_vacancy_readonly_val','val'=>'rct_vacancy_readonly_val','_val'=>'rct_vacancy_readonly_val',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy_readonly.list_exc','table'=>'_rct_vacancy_readonly');
 ?>