<?php $properties["fprops"]=array(
array('name'=>'archive_state','label'=>'archive_state','type'=>'text','value'=>'1','srcName'=>'archive_state','ufname'=>'_archive_state','qname'=>'rct_vacancy_action_archive_state','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('archive_state'=>'archive_state','_archive_state'=>'archive_state',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy_action.archive','table'=>'_rct_vacancy_action');
 ?>