<?php $properties["fprops"]=array(
array('name'=>'oid','label'=>'oid','type'=>'text','isKey'=>'primary','show'=>false,'srcName'=>'oid','ufname'=>'_oid','qname'=>'rct_vacancy_attached_file_oid','isEdit'=>false,'onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('oid'=>'oid','_oid'=>'oid',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy_attached_file.delete_by_poste','table'=>'_rct_vacancy_attached_file');
 ?>