<?php $properties["fprops"]=array(
array('name'=>'candidate_name','label'=>'candidate_name','type'=>'text','is_transient'=>true,'srcName'=>'candidate_name','ufname'=>'_candidate_name','qname'=>'rct_delayed_feedback_candidate_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'full_name','label'=>'full_name','type'=>'text','is_transient'=>true,'srcName'=>'full_name','ufname'=>'_full_name','qname'=>'rct_delayed_feedback_full_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'vacancy_name','label'=>'vacancy_name','type'=>'text','is_transient'=>true,'srcName'=>'vacancy_name','ufname'=>'_vacancy_name','qname'=>'rct_delayed_feedback_vacancy_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'to','label'=>'to','type'=>'text','is_transient'=>true,'srcName'=>'to','ufname'=>'_to','qname'=>'rct_delayed_feedback_to','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'subject','label'=>'subject','type'=>'text','is_transient'=>true,'srcName'=>'subject','ufname'=>'_subject','qname'=>'rct_delayed_feedback_subject','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),
array('name'=>'body','label'=>'body','type'=>'text','is_transient'=>true,'srcName'=>'body','ufname'=>'_body','qname'=>'rct_delayed_feedback_body','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('candidate_name'=>'candidate_name','_candidate_name'=>'candidate_name','full_name'=>'full_name','_full_name'=>'full_name','vacancy_name'=>'vacancy_name','_vacancy_name'=>'vacancy_name','to'=>'to','_to'=>'to','subject'=>'subject','_subject'=>'subject','body'=>'body','_body'=>'body',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_delayed_feedback.email_data','table'=>'_rct_delayed_feedback');
 ?>