<?php $properties["fprops"]=array(
array('name'=>'name','label'=>'name','type'=>'text','size'=>'200','srcName'=>'name','ufname'=>'_name','qname'=>'rct_vacancy_project_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('name'=>'name','_name'=>'name',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'vacancy_project.search','table'=>'_rct_vacancy_project');
 ?>