<?php $properties["fprops"]=array(
array('name'=>'count_recrute','label'=>'count_recrute','type'=>'text','srcName'=>'count_recrute','ufname'=>'_count_recrute','qname'=>'rct_vacancy_count_recrute','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('count_recrute'=>'count_recrute','_count_recrute'=>'count_recrute',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'vacancy_rekrute_count','table'=>'_rct_vacancy');
 ?>