ALTER TABLE `_rct_candidate` CHANGE `_civility` `_civility` TINYINT( 11 ) NULL DEFAULT NULL;
ALTER TABLE `_rct_candidate` CHANGE `_civility` `_civility` TINYINT( 3 ) NULL DEFAULT NULL;
ALTER TABLE `_rct_candidate` CHANGE `_gender` `_gender` TINYINT( 3 ) NULL DEFAULT NULL ;
ALTER TABLE `_rct_candidate` CHANGE `_nationality` `_nationality` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ;
ALTER TABLE `_rct_candidate` CHANGE `_email` `_email` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_phone_1` `_phone_1` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_phone_2` `_phone_2` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_mobile` `_mobile` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_years_of_practice` `_years_of_practice` SMALLINT( 11 ) NULL DEFAULT NULL ;
ALTER TABLE `_rct_candidate` CHANGE `_studies_level` `_studies_level` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_diploma` CHANGE `_code` `_code` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_diploma` CHANGE `_label` `_label` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_diploma` ADD INDEX ( `_code` ) ;
ALTER TABLE `_rct_school` CHANGE `_code` `_code` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_school` CHANGE `_label` `_label` VARCHAR( 200 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '';
ALTER TABLE `_rct_school` CHANGE `_label` `_label` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ;
ALTER TABLE `_rct_school` CHANGE `_label` `_label` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_school` ADD INDEX ( `_code` );
ALTER TABLE `_rct_candidate` CHANGE `_first_name` `_first_name` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_last_name` `_last_name` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_nationality` `_nationality` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_email` `_email` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_phone_1` `_phone_1` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_profile` `_profile` VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_available_delai` `_available_delai` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_bachelor_school` `_bachelor_school` VARCHAR( 400 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_age` `_age` TINYINT( 11 ) NULL DEFAULT NULL;
ALTER TABLE `_rct_candidate` CHANGE `_bachelor_title` `_bachelor_title` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_cl_path` `_cl_path` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NULL DEFAULT '';
ALTER TABLE `_rct_candidate` CHANGE `_cv_path` `_cv_path` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci  NULL DEFAULT '';
ALTER TABLE `_rct_candidate_vacancy_action` CHANGE `_user_oid` `_user_oid` INT( 11 ) NULL DEFAULT NULL;
ALTER TABLE `_rct_candidate_etat` CHANGE `_name` `_name` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate_etat` CHANGE `_index` `_index` VARCHAR( 10 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate_etat` CHANGE `_tasktype` `_tasktype` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate_comment` CHANGE `_comment` `_comment` TINYTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate_category` CHANGE `_name` `_name` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_candidate_client` CHANGE `_proposed_by` `_proposed_by` INT NULL DEFAULT NULL;
ALTER TABLE `_rct_candidate_client` CHANGE `_proposed_to` `_proposed_to` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `_rct_service` CHANGE `_name` `_name` VARCHAR( 300 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_short_list` CHANGE `_name` `_name` VARCHAR( 300 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_employment` CHANGE `_type` `_type` TINYINT( 3 ) NULL DEFAULT NULL;
ALTER TABLE `_rct_education` CHANGE `_diploma_type` `_diploma_type` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `_rct_email` CHANGE `_email_title` `_email_title` VARCHAR( 500 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
