<?php $properties["fprops"]=array(
array('name'=>'count','label'=>'line','type'=>'text','is_transient'=>true,'srcName'=>'count','ufname'=>'_count','qname'=>'rct_candidate_count','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('count'=>'count','_count'=>'count',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_candidate.count_candidate','table'=>'_rct_candidate');
 ?>