<?php $properties["fprops"]=array(
array('name'=>'count','label'=>'count','type'=>'text','srcName'=>'count','ufname'=>'_count','qname'=>'rct_candidate_count','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('count'=>'count','_count'=>'count',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'candidates.count.by_job_provider','table'=>'_rct_candidate');
 ?>