<?php $properties["fprops"]=array(
array('name'=>'country_name','label'=>'country_name','type'=>'text','srcName'=>'country_name','ufname'=>'_country_name','qname'=>'directory_country_country_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('country_name'=>'country_name','_country_name'=>'country_name',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'directory_country.search','table'=>'_directory_country');
 ?>