<?php $properties["fprops"]=array(
array('name'=>'integration_date','label'=>'integration_date','type'=>'date','srcName'=>'integration_date','ufname'=>'_integration_date','qname'=>'rct_candidate_integration_date','onSubmitCheck'=>"checkDate('%3\$s',%1\$s.%2\$s_day,%1\$s.%2\$s_month,%1\$s.%2\$s_year,%4\$s)",),);
$properties["falias"]=array('integration_date'=>'integration_date','_integration_date'=>'integration_date',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_candidate.set_integration_date','table'=>'_rct_candidate');
 ?>