<?php $properties["fprops"]=array(
array('name'=>'video_link','label'=>'video_link','type'=>'text','srcName'=>'video_link','ufname'=>'_video_link','qname'=>'rct_interview_video_link','size'=>'500','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('video_link'=>'video_link','_video_link'=>'video_link',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_interview.update_video_link','table'=>'_rct_interview');
 ?>