<?php $properties["fprops"]=array(
array('name'=>'comments_cache','label'=>'comments_cache','type'=>'text','value'=>$props->getProperty("comments_cache","",true),'srcName'=>'comments_cache','ufname'=>'_comments_cache','qname'=>'rct_candidate_comments_cache','onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('comments_cache'=>'comments_cache','_comments_cache'=>'comments_cache',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_candidate.edit_comments_cache','table'=>'_rct_candidate');
 ?>