<?php $properties["fprops"]=array(
array('name'=>'interviewer_email_not','label'=>'interviewer_email_not','type'=>'text_choice','list'=>'recruitment.boolean_list_3','sqltype'=>'integer','control'=>'checkbox','multiple'=>false,'default'=>'0','srcName'=>'interviewer_email_not','ufname'=>'_interviewer_email_not','qname'=>'rct_interview_interviewer_email_not','onSubmitCheck'=>"checkSelect('%3\$s',(%1\$s.%2\$s||%1\$s['%2\$s[]']),%4\$s)",),);
$properties["falias"]=array('interviewer_email_not'=>'interviewer_email_not','_interviewer_email_not'=>'interviewer_email_not',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_interview.edit_interviewer_email_not','table'=>'_rct_interview');
 ?>