<?php $properties["fprops"]=array(
array('name'=>'rct_vacancy_oid','label'=>'oid','type'=>'text','isKey'=>'primary','srcName'=>'oid','ufname'=>'rct_vacancy_oid','qname'=>'rct_vacancy_oid','show'=>false,'isEdit'=>false,'onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('oid'=>'rct_vacancy_oid','oid'=>'rct_vacancy_oid','_oid'=>'rct_vacancy_oid',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy.by_user_and_candidate','table'=>'_rct_vacancy');
 ?>