<?php $properties["fprops"]=array(
array('name'=>'is_default','label'=>'is_default','type'=>'text_choice','list'=>'recruitment.boolean_list','control'=>'checkbox_boolean','value'=>'0','srcName'=>'is_default','ufname'=>'_is_default','qname'=>'rct_search_params_is_default','onSubmitCheck'=>"checkSelect('%3\$s',(%1\$s.%2\$s||%1\$s['%2\$s[]']),%4\$s)",),);
$properties["falias"]=array('is_default'=>'is_default','_is_default'=>'is_default',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'search_params.not_default','table'=>'_rct_search_params');
 ?>