<?php $list=array(
'0' => 'Poste ouvert',
'1' => 'Validation de la demande d\'ouverture',
'2' => 'Sollicitation de cabinets de recrutement',
'3' => 'Association de CV au poste',
'4' => 'Envoi de candidats aux managers',
'5' => 'Envoi de short-list aux managers',
'6' => 'Planification d\'entretiens',
'7' => 'Acceptation de proposition',
'8' => 'Refus de proposition',
'9' => 'Candidat(s) retenu(s) pour le poste',
'10' => 'Sélection de candidat(s) annulée',
'11' => 'Evaluation ajoutée pour un candidat associé',
); ?>