<?php $list=array(
'0' => 'Open vacancy',
'1' => 'Validation of opening request',
'2' => 'Sent to recruitement agencies',
'3' => 'Resume attached to job',
'4' => 'Candidate sent to internal clients',
'5' => 'Send short-list to internal clients',
'6' => 'Interview planning',
'7' => 'Proposal acceptatance',
'8' => 'Proposal refusal',
'9' => 'Candidate(s) accepted for the job',
'10' => 'Selection of candidate(s) cancelled',
'11' => 'Proposal(s) sent',
); ?>