<?php $list=array(
'hello' => 'Bonjour',
'delayed_feedback_email_subject' => 'Evaluation à froid de ',
'delayed_feedback_email_chunk1' => 'Vous êtes prié de saisir une évaluation à froid concernant le recrutement de',
'delayed_feedback_email_chunk2' => 'pour le poste',
'delayed_feedback_email_chunk3' => 'Connectez-vous sur l\'intranet afin de la remplir',
'delayed_feedback_email_chunk4' => 'Cordialement,',
'warning_title' => 'Rappel: ',
'warning_chunk1' => 'Le rappel suivant a été programmé dans l\'intranet RH:',
); ?>