<?php $properties["fprops"]=array(
array('name'=>'town_name','label'=>'town_name','type'=>'text','srcName'=>'town_name','ufname'=>'_town_name','qname'=>'directory_town_town_name','multiLines'=>false,'onSubmitCheck'=>"checkText('%3\$s',%1\$s.%2\$s,%4\$s)",),);
$properties["falias"]=array('town_name'=>'town_name','_town_name'=>'town_name',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'directory_town.search','table'=>'_directory_town');
 ?>