<?php $properties["fprops"]=array(
array('name'=>'archive_state','type'=>'text','value'=>'1','label'=>'archive_state','srcName'=>'archive_state','ufname'=>'_archive_state','qname'=>'rct_candidate_archive_state','list'=>'recruitment.archive_state','control'=>'select','sqltype'=>'integer','multiple'=>false,'default'=>'0','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('archive_state'=>'archive_state','_archive_state'=>'archive_state',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_candidate.archive','table'=>'_rct_candidate');
 ?>