<?php $properties["fprops"]=array(
array('name'=>'oid','type'=>'text','label'=>'oid','srcName'=>'oid','ufname'=>'_oid','qname'=>'rct_vacancy_oid','isKey'=>'primary','show'=>false,'isEdit'=>false,'onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('oid'=>'oid','_oid'=>'oid',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_vacancy.manager_permission','table'=>'_rct_vacancy');
 ?>