<?php $properties["fprops"]=array(
array('name'=>'date','is_transient'=>true,'type'=>'date','label'=>'date','srcName'=>'date','ufname'=>'_date','qname'=>'rct_candidate_vacancy_date','onSubmitCheck'=>"checkDate('%3\$s',%1\$s.%2\$s_day,%1\$s.%2\$s_month,%1\$s.%2\$s_year,%4\$s)",),);
$properties["falias"]=array('date'=>'date','_date'=>'date',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_candidate_vacancy.handle_proposal','table'=>'_rct_candidate_vacancy');
 ?>