<?php $properties["fprops"]=array(
array('name'=>'notification_state','type'=>'text','value'=>'1','label'=>'notification_state','srcName'=>'notification_state','ufname'=>'_notification_state','qname'=>'rct_warning_notification_state','onInput'=>"keypress_number(event)",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('notification_state'=>'notification_state','_notification_state'=>'notification_state',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'rct_warning.change_notification_state','table'=>'_rct_warning');
 ?>