
<?php
$properties=array(
	'providers' => array(
		'reckrute' => array(
			'active'=>true,
			'job_board.method'=>'ftp',
			'job_board.ftp.host'=>'188.165.35.98',
			'job_board.ftp.port'=>'21',
			'job_board.ftp.user'=>'defaultpresence',
			'job_board.ftp.password'=>'fh897njt7',
			'job_board.ftp.dir'=>'/home/presencemedia/domains/intranet.presencemedia.ma/public_html/intranet/generis2011/packages/recruitment/tmp',
			'job_board.xml_format'=>'reckrute',
			'job_board.soap.host'=>'www.rekrute.com',
			'job_board.soap.user'=>'test',
			'jobs_board.files.tmp_path' => GENERIS_PACKAGES.'recruitment/tmp/',

			),
		),
);

?>
